name: 'Transfer Table Test Scrape'
description: 'Composite action to perform scraping for a particular state with testing data'
inputs:
  state-number: 
    description: 'Which state number'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Installed package list
      run: apt list --installed
      shell: bash
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
      shell: bash
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
      shell: bash
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser
      shell: bash
    - name: Install all necessary packages
      run: pip install selenium chromedriver_autoinstaller pandas
      shell: bash
    - name: Run scraping
      run: python public/data/transfer_table_scrape_test.py ${{ inputs.state-number }}
      shell: bash
    - name: Upload artifact
      uses: actions/checkout@v3
      with:
        name: ${{ inputs.state-number }}_test
        path: 'public/data/all_data_test/${{ inputs.state-number }}_test.json'

