name: JSON Formatter for Full Scrape

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Transfer Table Full Scrape Workflow"]
    types:
      - completed

jobs:
  format:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install all necessary packages
        run: pip install pandas
      - name: Combine individual state outputs
        run: python public/data/combine_state_output.py all_data
      - name: Create formatted search fields
        run: python public/data/format_search_fields.py all_data
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
