name: Push to Typesense

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["JSON Formatter for Full Scrape"]
    types:
      - completed

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install all necessary packages
        run: pip install typesense pandas python-dotenv
      - name: Push searches to Typesense
        run: python public/data/typesense_data_config.py searches searches 0 ${{secrets.TYPESENSE_ADMIN_API_KEY}} ${{secrets.TYPESENSE_HOST}} ${{secrets.TYPESENSE_PORT}} ${{secrets.TYPESENSE_PROTOCOL}}
      - name: Push transfers to Typesense
        run: python public/data/typesense_data_config.py transfers transfers 0 ${{secrets.TYPESENSE_ADMIN_API_KEY}} ${{secrets.TYPESENSE_HOST}} ${{secrets.TYPESENSE_PORT}} ${{secrets.TYPESENSE_PROTOCOL}}
