name: transfer_table_scrape-test
on:
  workflow_dispatch:
  push:
    paths:
      - 'public/data/transfer_table_scrape_test.py'
jobs:
  scrape_0:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_0
        uses: .github/actions/tt_scrape
        with:
          state-number: 0
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

