name: Transfer Table Full Scrape Workflow
on:
  workflow_dispatch:
  push:
    paths:
      - "public/data/transfer_table_scrape.py"
  schedule:
    - cron: '0 0 1 * *'
jobs:
  scrape_1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_1
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 1
  scrape_2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_2
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 2
  scrape_3:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_3
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 3
  scrape_4:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_4
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 4
  scrape_5:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_5
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 5
  scrape_6:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_6
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 6
  scrape_7:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_7
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 7
  scrape_8:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_8
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 8
  scrape_9:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_9
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 9
  scrape_10:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_10
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 10
  scrape_11:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_11
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 11
  scrape_12:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_12
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 12
  scrape_13:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_13
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 13
  scrape_14:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_14
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 14
  scrape_15:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_15
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 15
  scrape_16:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_16
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 16
  scrape_17:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_17
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 17
  scrape_18:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_18
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 18
  scrape_19:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_19
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 19
  scrape_20:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_20
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 20
  scrape_21:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_21
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 21
  scrape_22:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_22
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 22
  scrape_23:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_23
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 23
  scrape_24:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_4
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 24
  scrape_25:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_5
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 25
  scrape_26:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_6
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 26
  scrape_27:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_7
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 27
  scrape_28:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_8
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 28
  scrape_29:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_9
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 29
  scrape_30:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_30
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 30
  scrape_31:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_31
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 31
  scrape_32:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_32
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 32
  scrape_33:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_33
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 33
  scrape_34:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_34
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 34
  scrape_35:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_35
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 35
  scrape_36:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_36
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 36
  scrape_37:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_7
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 37
  scrape_38:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_38
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 38
  scrape_39:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_39
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 39
  scrape_40:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_40
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 40
  scrape_41:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_41
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 41
  scrape_42:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_42
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 42
  scrape_43:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_43
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 43
  scrape_44:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_44
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 44
  scrape_45:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_5
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 45
  scrape_46:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_46
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 46
  scrape_47:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_7
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 47
  scrape_48:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_48
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 48
  scrape_49:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_49
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 49
  scrape_50:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_50
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 50
  scrape_51:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_51
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 51
  scrape_52:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_52
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 52
  scrape_53:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_53
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 53
  scrape_54:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - id: scrape_54
        uses: ./.github/actions/tt_scrape
        with:
          state-number: 54
  final:
    runs-on: ubuntu-latest
    needs:
      [
        scrape_1,
        scrape_2,
        scrape_3,
        scrape_4,
        scrape_5,
        scrape_6,
        scrape_7,
        scrape_8,
        scrape_9,
        scrape_10,
        scrape_11,
        scrape_12,
        scrape_13,
        scrape_14,
        scrape_15,
        scrape_16,
        scrape_17,
        scrape_18,
        scrape_19,
        scrape_20,
        scrape_21,
        scrape_22,
        scrape_23,
        scrape_24,
        scrape_25,
        scrape_26,
        scrape_27,
        scrape_28,
        scrape_29,
        scrape_30,
        scrape_31,
        scrape_32,
        scrape_33,
        scrape_34,
        scrape_35,
        scrape_36,
        scrape_37,
        scrape_38,
        scrape_39,
        scrape_40,
        scrape_41,
        scrape_42,
        scrape_43,
        scrape_44,
        scrape_45,
        scrape_46,
        scrape_47,
        scrape_48,
        scrape_49,
        scrape_50,
        scrape_51,
        scrape_52,
        scrape_53,
        scrape_54,
      ]
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Git Pull
        run: git pull
      - name: Remove existing all_data directory
        run: rm -rf ./public/data/output/all_data
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ./public/data/output/all_data
      - name: git status
        run: git status
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
